server:
  port: 8090
  servlet:
    context-path: /api/job-seekers
spring:
  application:
    name: ms-job-seekers
  datasource:
    url: jdbc:postgresql://localhost:5432/service_job_seekers6
    username: imadmansour
    password: imadmansour
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  kafka:
    consumer:
      group-id: "default"

topic:
  job-seekers:
    create-job-request: job-seekers.create-job-request
