server:
  port: 8090
spring:
  application:
    name: ms-job-seekers
  datasource:
    password: imadmansour
    url: jdbc:postgresql://localhost:5432/ms_job_seekers
    username: imadmansour
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
